# -*- coding: utf-8 -*-
"""抖音下载器 - yt-dlp 适配后端。"""
from __future__ import annotations

import os
import re
import json
import shutil
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from backends.venv_manager import (
    ensure_external_dirs,
    secure_write_text,
    cleanup_paths,
    run_supervised,
    parse_cookie_header,
    ExternalBackendError,
    RUNTIME_DIR,
    YT_DLP_ARCHIVE,
)
from utils.logger import setup_logger

logger = setup_logger("YtDlpBackend")


@dataclass
class YtDlpItem:
  media_id: str
  title: str
  uploader: str
  extractor: str
  webpage_url: str
  audio_path: Path
  info: dict[str, Any]
  temporary_root: Path


@dataclass
class YtDlpProbeItem:
  media_id: str
  title: str
  uploader: str
  extractor: str
  webpage_url: str


def write_netscape_cookie_file(cookie_str: str, path: Path, domain: str = ".douyin.com") -> None:
  lines = [
    "# Netscape HTTP Cookie File",
    "# Generated by douyin-fetcher-standalone.",
  ]
  for key, value in parse_cookie_header(cookie_str).items():
    safe_value = value.replace("\n", "").replace("\r", "")
    lines.append(f"{domain}\tTRUE\t/\tTRUE\t0\t{key}\t{safe_value}")
  secure_write_text(path, "\n".join(lines) + "\n")


def run_ytdlp_audio(
  *,
  url: str,
  cookie_str: str = "",
  use_douyin_cookie: bool = False,
) -> list[YtDlpItem]:
  yt_dlp_bin = shutil.which("yt-dlp")
  if not yt_dlp_bin:
    raise ExternalBackendError("未检测到 yt-dlp，请先安装 yt-dlp 或改用 legacy 后端。")

  ensure_external_dirs()
  run_dir = RUNTIME_DIR / f"yt-dlp-{os.getpid()}"
  cookie_path = RUNTIME_DIR / f"yt-dlp-cookies-{os.getpid()}.txt"
  cleanup_targets = [cookie_path]
  run_dir.mkdir(parents=True, exist_ok=True)

  output_template = "%(extractor_key|external)s/%(id)s/%(id)s.%(ext)s"
  cmd = [
    yt_dlp_bin,
    "--ignore-errors",
    "--no-progress",
    "--write-info-json",
    "--download-archive",
    str(YT_DLP_ARCHIVE),
    "--extract-audio",
    "--audio-format",
    "mp3",
    "--paths",
    str(run_dir),
    "--output",
    output_template,
    url,
  ]
  if cookie_str and use_douyin_cookie:
    write_netscape_cookie_file(cookie_str, cookie_path)
    cmd[1:1] = ["--cookies", str(cookie_path)]

  try:
    result = run_supervised(cmd, cookie_str=cookie_str)
    if result.returncode != 0:
      details = result.stderr.strip() or result.stdout.strip()
      raise ExternalBackendError(f"yt-dlp 下载失败: {details}")
    return scan_ytdlp_outputs(run_dir)
  finally:
    cleanup_paths(cleanup_targets)


def probe_ytdlp_items(
  *,
  url: str,
  cookie_str: str = "",
  use_douyin_cookie: bool = False,
) -> list[YtDlpProbeItem]:
  yt_dlp_bin = shutil.which("yt-dlp")
  if not yt_dlp_bin:
    raise ExternalBackendError("未检测到 yt-dlp，请先安装 yt-dlp 或改用 legacy 后端。")

  ensure_external_dirs()
  cookie_path = RUNTIME_DIR / f"yt-dlp-probe-cookies-{os.getpid()}.txt"
  cleanup_targets = [cookie_path]
  cmd = [
    yt_dlp_bin,
    "--ignore-errors",
    "--no-progress",
    "--flat-playlist",
    "--dump-json",
    url,
  ]
  if cookie_str and use_douyin_cookie:
    write_netscape_cookie_file(cookie_str, cookie_path)
    cmd[1:1] = ["--cookies", str(cookie_path)]

  try:
    result = run_supervised(cmd, cookie_str=cookie_str)
    if result.returncode != 0:
      details = result.stderr.strip() or result.stdout.strip()
      raise ExternalBackendError(f"yt-dlp 列表探测失败: {details}")
    items: list[YtDlpProbeItem] = []
    for line in result.stdout.splitlines():
      line = line.strip()
      if not line:
        continue
      try:
        info = json.loads(line)
      except json.JSONDecodeError:
        continue
      media_id = str(info.get("id") or info.get("url") or "").strip()
      if not media_id:
        continue
      items.append(
        YtDlpProbeItem(
          media_id=media_id,
          title=str(info.get("title") or media_id),
          uploader=str(info.get("uploader") or info.get("channel") or ""),
          extractor=str(info.get("extractor_key") or info.get("extractor") or ""),
          webpage_url=str(info.get("webpage_url") or info.get("url") or ""),
        )
      )
    return items
  finally:
    cleanup_paths(cleanup_targets)


def scan_ytdlp_outputs(root: Path) -> list[YtDlpItem]:
  items: list[YtDlpItem] = []
  if not root.exists():
    return items

  for info_path in root.rglob("*.info.json"):
    try:
      info = json.loads(info_path.read_text(encoding="utf-8"))
    except Exception as exc:
      logger.warning("读取 yt-dlp 元数据失败 %s: %s", info_path, exc)
      continue

    media_id = str(info.get("id") or info_path.stem.replace(".info", "")).strip()
    title = str(info.get("title") or media_id or "untitled")
    uploader = str(info.get("uploader") or info.get("channel") or "external")
    extractor = str(info.get("extractor_key") or info.get("extractor") or "external")
    webpage_url = str(info.get("webpage_url") or "")

    candidates = sorted(
      p for p in info_path.parent.glob(f"{media_id}.*")
      if p.is_file() and not p.name.endswith(".info.json")
    )
    audio_path = next((p for p in candidates if p.suffix.lower() == ".mp3"), None)
    if not audio_path and candidates:
      audio_path = candidates[0]
    if not audio_path:
      logger.warning("yt-dlp 元数据存在但未找到媒体文件: %s", info_path)
      continue

    items.append(
      YtDlpItem(
        media_id=media_id,
        title=title,
        uploader=uploader,
        extractor=extractor,
        webpage_url=webpage_url,
        audio_path=audio_path,
        info=info,
        temporary_root=root,
      )
    )

  return items


def looks_like_douyin_url(url: str) -> bool:
  return bool(re.search(r"(^|//|\.)(douyin|iesdouyin)\.com", url))
